---
functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории.
- Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.

non-functional:
- Сайт должен быть способен обрабатывать большое количество трафика.
- Сайт должен быть протестирован на совместимость с последними версиями браузеров.
- Сайт должен быть безопасным и защищать данные пользователя.
- Сайт должен иметь мобильную версию.
- Сайт должен быть способен обрабатывать большое количество трафика.
- Сайт должен быть доступен на различных устройствах.
- Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.

implicit: 
- необходима регистрация и указание конатных данных для офрлмения заказа
- Поля формы регистрации должны заполняться корректо
- Пользователь должен иметь возможность выбрать вид доставки 
- Пользователь должен иметь возможность выбора формы оплаты 
- Сайт должен быть итегрироваван с системами платежей. Яндекс.Касса, ROBOKASSA
- сайт должен иметь инструменты маркетинга. Скидки,купоны, рекомендации.
- Сайт должен позволять вести учет количества товаров.
- Полное описание товара в карточке товара
- В карточке товара поле для коментриев и отзывов
- Чат с администраций магазина
- При переключении языка переводится весь контект, кроме названия брендов.





